import { useState, useContext } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { LitNodeClient } from "@lit-protocol/lit-node-client";
import { LitNetwork } from "@lit-protocol/constants";
import { checkAndSignAuthMessage } from "@lit-protocol/auth-browser";
import Cookies from 'js-cookie'
import { UUIDContext } from '../context'

const accessControlConditions = [
  {
    contractAddress: '',
    standardContractType: '',
    chain: 'verifyTestnet',
    method: '',
    parameters: [
      ':userAddress',
    ],
    returnValueTest: {
      comparator: '=',
      value: '0xaB9BE0f5521B121b738d29EAcD3683F22F38eCF0'
    }
  }]


export default function Home() {
  const [connected, setConnected] = useState()
  const [jwtIssued, setJwtIssued] = useState();
  const { id } = useContext(UUIDContext)

  async function connect() {
    const resourceId = {
      baseUrl: 'http://localhost:3000',
      path: '/protected',
      orgId: "",
      role: "",
      extraData: id
    }

    const client = new LitNodeClient({ litNetwork: LitNetwork.DatilDev })
    await client.connect()
    const authSig = await checkAndSignAuthMessage({chain: 'verifyTestnet'})
    try {
      const jwt = await client.getSignedToken({
        accessControlConditions, chain: 'verifyTestnet', authSig, resourceId: resourceId
      })
      Cookies.set('lit-auth', jwt, { expires: 1 })
      setJwtIssued(jwt);
      setConnected(true)
    } catch (err) {
      console.log('error: ', err)
    }
    await client.disconnect();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Developer DAO Access</h1>
      {
        !connected ? <button onClick={connect}>Connect</button> :  <><p>Access Granted</p><textarea style={{width: '70vw',height: '100px'}}>{jwtIssued}</textarea></>
      }

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
